"""Add project_categories table

Revision ID: 23327ef700dd
Revises: 08d16cd78743
Create Date: 2026-02-18 12:54:48.454798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23327ef700dd'
down_revision: Union[str, Sequence[str], None] = '08d16cd78743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assigned_vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_vendor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_categories_id'), 'project_categories', ['id'], unique=False)
    # op.drop_table('system_settings')
    op.add_column('project_requirements', sa.Column('category', sa.String(), nullable=True))
    op.add_column('project_requirements', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('project_requirements', sa.Column('field_type', sa.String(), nullable=False, server_default='file'))
    op.create_foreign_key(None, 'project_requirements', 'project_categories', ['category_id'], ['id'])
    op.add_column('submittals', sa.Column('category', sa.String(), nullable=True))
    op.add_column('submittals', sa.Column('ai_processing_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_submittals_category'), 'submittals', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submittals_category'), table_name='submittals')
    op.drop_column('submittals', 'ai_processing_status')
    op.drop_column('submittals', 'category')
    op.drop_constraint(None, 'project_requirements', type_='foreignkey')
    op.drop_column('project_requirements', 'field_type')
    op.drop_column('project_requirements', 'category_id')
    op.drop_column('project_requirements', 'category')
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey')),
    sa.UniqueConstraint('key', name=op.f('system_settings_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_project_categories_id'), table_name='project_categories')
    op.drop_table('project_categories')
    # ### end Alembic commands ###
